### ISSUE TITLE
websocket

### ISSUE THREAD

**Issue by Carolineliu** [k55k32/you-draw-i-guess#1]
你好，我在vue里面用websocket，连接时会报302，连不上，有没有解决的办法，谢谢

**Comment by diamondfsd** [comment]
看一下配置的ip是不是正确的呀。
在源文件中的 `main.js` 里面可以更改你 websocket 服务器的的ip地址

**Comment by Carolineliu** [comment]
你好，你这代码没有问题，我只是想请教你一下。我们开发的前后端不在同一个域下，所以老是报跨域问题不知道你有什么方法解决吗

**Comment by diamondfsd** [comment]
ws 好像没有跨域问题，因为我在项目中用的是 ip 地址直接连接的，也没有报错。
如果是http 的话，就需要服务端对跨域请求头的支持。或者自己写一个中间代理层来完成请求。

**Comment by Carolineliu** [comment]
谢谢
